server:
  port: 8711
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lanzhu259X/spring-cloud-study/
          search-paths: config
          username: lanzhu259X
          password: xxxx
  profiles:
    active: master

eureka:
  client:
    service-url:
      defaultZone: http://discovery-eureka-master:8761/eureka/,http://discovery-eureka-slaveone:8761/eureka/

